analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.093468
  lightness: 0.787162
  rhythmicContrast: 0.782657
  saturation: 0.909909
cta: {}
layout_spectrum: 0.855855
name: Las Vueltas al Mundo
opengraph: {}
purpose: []
title: LVAM
typography_spectrum: 0.711711
