name: Las Vueltas al Mundo
favicon: null
layout_spectrum: 0.23536
typography_spectrum: 0
title: LVAM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2d2427'
    - '#956a48'
    - '#f89d5a'
    - '#f3e85e'
  brandStrength: 0.980855
  lightness: 0.951576
  saturation: 0
  rhythmicContrast: 1
purpose: []
