name: Las Vueltas al Mundo
favicon: null
layout_spectrum: 0.93354
typography_spectrum: 0.69906
title: LVAM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2d2427'
    - '#956a48'
    - '#f89d5a'
    - '#f3e85e'
  brandStrength: 0.093468
  lightness: 0.787162
  saturation: 0.6875
  rhythmicContrast: 0.782657
purpose: []
