name: Las Vueltas al Mundo
favicon: null
layout_spectrum: 0.11573025537654757
typography_spectrum: 0.5834303733427078
title: LVAM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09083332680165768
  lightness: 0.6507483816239983
  saturation: 0.8956202259287238
  rhythmicContrast: 0.11069564567878842
purpose: []
