analytics: {}
color:
  brandColors:
    - '#FBE24A'
    - '#0F0D01'
    - '#FEF3BB'
    - '#E1C847'
    - '#FDEE87'
  brandStrength: 0
  lightness: 0.666666
  rhythmicContrast: 0.745495
  saturation: 0.628378
cta: {}
layout_spectrum: 0.245495
name: Las Vueltas al Mundo
opengraph: {}
purpose: []
title: LVAM
typography_spectrum: 1
