analytics: {}
color:
  brandColors:
    - '#fefefe'
    - '#2d2427'
    - '#956a48'
    - '#f89d5a'
    - '#f3e85e'
  brandStrength: 0.980855
  lightness: 0.951576
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.23536
name: Las Vueltas al Mundo
opengraph: {}
purpose: []
title: LVAM
typography_spectrum: 0.69906
