analytics: {}
color:
  brandColors:
    - '#fefefe'
    - '#2d2427'
    - '#956a48'
    - '#f89d5a'
    - '#f3e85e'
  brandStrength: 0.944819
  lightness: 0.945945
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.765765
name: Las Vueltas al Mundo
opengraph: {}
purpose: []
title: LVAM
typography_spectrum: 1
