analytics: {}
color:
  brandColors:
    - '#fefefe'
    - '#2d2427'
    - '#956a48'
    - '#f89d5a'
    - '#f3e85e'
  brandStrength: 0.944819
  lightness: 0.666666
  rhythmicContrast: 0.252252
  saturation: 0.628378
cta: {}
layout_spectrum: 0.108108
name: Las Vueltas al Mundo
opengraph: {}
purpose: []
title: LVAM
typography_spectrum: 1
