name: Las Vueltas al Mundo
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6182f4af-3010-4439-9363-2a6f0267ffe1.jpg
layout_spectrum: 0.245495
typography_spectrum: 1
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FBE24A'
    - '#0F0D01'
    - '#FEF3BB'
    - '#E1C847'
    - '#FDEE87'
  brandStrength: 0
  lightness: 0.666666
  saturation: 0.628378
  rhythmicContrast: 0.745495
purpose: []
title: LVAM
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
